ResourceMap = {
    "aliyun.ecs": "c7n_aliyun.resources.ecs.Ecs",
    "aliyun.disk": "c7n_aliyun.resources.disk.Disk",
    "aliyun.vpc": "c7n_aliyun.resources.vpc.Vpc",
    "aliyun.security-group": "c7n_aliyun.resources.vpc.SecurityGroup",
    "aliyun.app-engine": "c7n_aliyun.resources.appengine.AppEngineApp",
    "aliyun.app-engine-certificate": "c7n_aliyun.resources.appengine.AppEngineCertificate",
    "aliyun.app-engine-domain": "c7n_aliyun.resources.appengine.AppEngineDomain",
    "aliyun.app-engine-domain-mapping": "c7n_aliyun.resources.appengine.AppEngineDomainMapping",
    "aliyun.app-engine-firewall-ingress-rule": (
        "c7n_aliyun.resources.appengine.AppEngineFirewallIngressRule"),
    "aliyun.autoscaler": "c7n_aliyun.resources.compute.Autoscaler",
    "aliyun.bq-dataset": "c7n_aliyun.resources.bigquery.DataSet",
    "aliyun.bq-job": "c7n_aliyun.resources.bigquery.BigQueryJob",
    "aliyun.bq-project": "c7n_aliyun.resources.bigquery.BigQueryProject",
    "aliyun.bq-table": "c7n_aliyun.resources.bigquery.BigQueryTable",
    "aliyun.bucket": "c7n_aliyun.resources.storage.Bucket",
    "aliyun.build": "c7n_aliyun.resources.build.CloudBuild",
    "aliyun.cloudbilling-account": "c7n_aliyun.resources.cloudbilling.CloudBillingAccount",
    "aliyun.dataflow-job": "c7n_aliyun.resources.dataflow.DataflowJob",
    "aliyun.dm-deployment": "c7n_aliyun.resources.deploymentmanager.DMDeployment",
    "aliyun.dns-managed-zone": "c7n_aliyun.resources.dns.DnsManagedZone",
    "aliyun.dns-policy": "c7n_aliyun.resources.dns.DnsPolicy",
    "aliyun.firewall": "c7n_aliyun.resources.network.Firewall",
    "aliyun.folder": "c7n_aliyun.resources.resourcemanager.Folder",
    "aliyun.function": "c7n_aliyun.resources.function.Function",
    "aliyun.gke-cluster": "c7n_aliyun.resources.gke.KubernetesCluster",
    "aliyun.gke-nodepool": "c7n_aliyun.resources.gke.KubernetesClusterNodePool",
    "aliyun.iam-role": "c7n_aliyun.resources.iam.Role",
    "aliyun.image": "c7n_aliyun.resources.compute.Image",
    "aliyun.instance-template": "c7n_aliyun.resources.compute.InstanceTemplate",
    "aliyun.interconnect": "c7n_aliyun.resources.network.Interconnect",
    "aliyun.interconnect-attachment": "c7n_aliyun.resources.network.InterconnectAttachment",
    "aliyun.kms-cryptokey": "c7n_aliyun.resources.kms.KmsCryptoKey",
    "aliyun.kms-cryptokey-version": "c7n_aliyun.resources.kms.KmsCryptoKeyVersion",
    "aliyun.kms-keyring": "c7n_aliyun.resources.kms.KmsKeyRing",
    "aliyun.loadbalancer-address": "c7n_aliyun.resources.loadbalancer.LoadBalancingAddress",
    "aliyun.loadbalancer-backend-bucket": "c7n_aliyun.resources.loadbalancer.LoadBalancingBackendBucket",
    "aliyun.loadbalancer-backend-service": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingBackendService"),
    "aliyun.loadbalancer-forwarding-rule": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingForwardingRule"),
    "aliyun.loadbalancer-global-address": "c7n_aliyun.resources.loadbalancer.LoadBalancingGlobalAddress",
    "aliyun.loadbalancer-global-forwarding-rule": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingGlobalForwardingRule"),
    "aliyun.loadbalancer-health-check": "c7n_aliyun.resources.loadbalancer.LoadBalancingHealthCheck",
    "aliyun.loadbalancer-http-health-check": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingHttpHealthCheck"),
    "aliyun.loadbalancer-https-health-check": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingHttpsHealthCheck"),
    "aliyun.loadbalancer-ssl-certificate": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingSslCertificate"),
    "aliyun.loadbalancer-ssl-policy": "c7n_aliyun.resources.loadbalancer.LoadBalancingSslPolicy",
    "aliyun.loadbalancer-target-http-proxy": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetHttpProxy"),
    "aliyun.loadbalancer-target-https-proxy": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetHttpsProxy"),
    "aliyun.loadbalancer-target-instance": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetInstance"),
    "aliyun.loadbalancer-target-pool": "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetPool",
    "aliyun.loadbalancer-target-ssl-proxy": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetSslProxy"),
    "aliyun.loadbalancer-target-tcp-proxy": (
        "c7n_aliyun.resources.loadbalancer.LoadBalancingTargetTcpProxy"),
    "aliyun.loadbalancer-url-map": "c7n_aliyun.resources.loadbalancer.LoadBalancingUrlMap",
    "aliyun.log-exclusion": "c7n_aliyun.resources.logging.LogExclusion",
    "aliyun.log-project-metric": "c7n_aliyun.resources.logging.LogProjectMetric",
    "aliyun.log-project-sink": "c7n_aliyun.resources.logging.LogProjectSink",
    "aliyun.ml-job": "c7n_aliyun.resources.mlengine.MLJob",
    "aliyun.ml-model": "c7n_aliyun.resources.mlengine.MLModel",
    "aliyun.organization": "c7n_aliyun.resources.resourcemanager.Organization",
    "aliyun.project": "c7n_aliyun.resources.resourcemanager.Project",
    "aliyun.project-role": "c7n_aliyun.resources.iam.ProjectRole",
    "aliyun.pubsub-snapshot": "c7n_aliyun.resources.pubsub.PubSubSnapshot",
    "aliyun.pubsub-subscription": "c7n_aliyun.resources.pubsub.PubSubSubscription",
    "aliyun.pubsub-topic": "c7n_aliyun.resources.pubsub.PubSubTopic",
    "aliyun.route": "c7n_aliyun.resources.network.Route",
    "aliyun.router": "c7n_aliyun.resources.network.Router",
    "aliyun.service": "c7n_aliyun.resources.service.Service",
    "aliyun.service-account": "c7n_aliyun.resources.iam.ServiceAccount",
    "aliyun.snapshot": "c7n_aliyun.resources.compute.Snapshot",
    "aliyun.sourcerepo": "c7n_aliyun.resources.source.SourceRepository",
    "aliyun.spanner-database-instance": "c7n_aliyun.resources.spanner.SpannerDatabaseInstance",
    "aliyun.spanner-instance": "c7n_aliyun.resources.spanner.SpannerInstance",
    "aliyun.sql-backup-run": "c7n_aliyun.resources.sql.SqlBackupRun",
    "aliyun.sql-instance": "c7n_aliyun.resources.sql.SqlInstance",
    "aliyun.sql-ssl-cert": "c7n_aliyun.resources.sql.SqlSslCert",
    "aliyun.sql-user": "c7n_aliyun.resources.sql.SqlUser",
    "aliyun.subnet": "c7n_aliyun.resources.network.Subnet"
}
